const URL=window.CYBERMEDIEVAL_SUPABASE_URL||"",KEY=window.CYBERMEDIEVAL_SUPABASE_KEY||"",sb=URL&&KEY?supabase.createClient(URL,KEY):null;
const qs=[["IA","Qual técnica permite aprender padrões a partir de exemplos?",["Aprendizado de máquina","NAT","DNS","FTP"],0],["Redes","Qual protocolo traduz nomes de domínio em IP?",["HTTP","DNS","SSH","FTP"],1],["Linux","Qual comando lista arquivos?",["cd","pwd","ls","mkdir"],2],["Segurança","Qual prática reduz o impacto de uma senha comprometida?",["Desativar logs","MFA","Reutilizar senha","Abrir portas"],1],["Cisco","Qual dispositivo encaminha pacotes entre redes?",["Switch","Roteador","Hub","Access Point"],1],["Vulnerabilidades","O que é uma vulnerabilidade?",["Fraqueza explorável","Backup","Antivírus","Usuário"],0],["Endpoints","Um notebook corporativo conectado é um:",["Endpoint","DNS","Gateway","Firewall"],0],["Linux","Qual comando mostra o diretório atual?",["pwd","grep","touch","rm"],0],["Cisco","Qual protocolo permite administração remota segura?",["Telnet","SSH","FTP","HTTP"],1],["IA","Um sistema que classifica spam é exemplo de:",["Classificação","NAT","Criptografia","Roteamento"],0]];
const avatars=["🛡️ Cavaleiro Endpoint","🧙 Maga da Criptografia","⚡ Guardião Cisco","🐧 Hacker Linux","🤖 Sentinela IA"],weapons=["⚔️ Espada Firewall","🏹 Arco do Linux","🔱 Lança Cisco","🪄 Cajado IA","🛡️ Escudo Zero Trust"];
let s={name:"",room:"CASTELO-01",level:1,qi:0,xp:0,score:0,avatar:avatars[0],weapon:weapons[0],hp:100,channel:null};const app=document.querySelector("#app");
function toast(x){const e=document.createElement("div");e.className="toast";e.textContent=x;document.body.append(e);setTimeout(()=>e.remove(),2000)}
function lobby(){app.innerHTML='<main class="screen"><div class="shell hero"><section class="panel"><div class="brand">⚔ CyberMedieval Shield</div><h1 class="title">Defenda o Reino.<br>Domine a Tecnologia.</h1><p class="subtitle">Jornada educativa medieval cyberpunk por IA, redes, Linux, vulnerabilidades, endpoints e Cisco.</p><div class="grid"><div class="stat"><b>10</b>Níveis</div><div class="stat"><b>6</b>Jogadores</div><div class="stat"><b>∞</b>Desafios</div></div></section><section class="panel"><h2>🏰 Entrar no Reino</h2><label>Nome do jogador</label><input id="name" placeholder="Digite seu nome"><label>Código da sala</label><input id="room" value="CASTELO-01"><button id="go" style="width:100%;margin-top:14px">Entrar na aventura</button><p class="small">Níveis 1–5: Academia • Níveis 6–10: Arena multiplayer</p></section></div></main>';document.querySelector("#go").onclick=()=>{s.name=document.querySelector("#name").value.trim()||"Jogador";s.room=document.querySelector("#room").value.trim()||"CASTELO-01";quiz();presence()}}
function quiz(){const q=qs[s.qi%qs.length];app.innerHTML='<main class="screen"><div class="shell"><div class="topbar"><div><div class="brand">ACADEMIA CYBERMEDIEVAL</div><h2>Nível '+s.level+" · "+q[0]+'</h2></div><span class="pill">XP '+s.xp+" · ⭐ "+s.score+'</span></div><section class="panel"><p class="small">Desafio '+s.level+'/5</p><h2>'+q[1]+'</h2><div class="choices">'+q[2].map((a,i)=>'<button class="choice" data-i="'+i+'">'+a+"</button>").join("")+'</div></section><section class="panel" style="margin-top:14px"><div class="grid"><div class="card">🧙 '+s.avatar+'</div><div class="card">⚔️ '+s.weapon+'</div><div class="card">🏆 '+s.score+' pontos</div></div></section></div></main>';document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>answer(+b.dataset.i,q))}
function answer(i,q){document.querySelectorAll(".choice").forEach(b=>b.disabled=true);if(i===q[3]){s.score+=100;s.xp+=50;toast("⚡ Acerto! +100 pontos");if(s.level<5){s.level++;setTimeout(reward,600)}else{s.level=6;setTimeout(arena,700)}}else{toast("🛡️ Resposta incorreta — turno/conceito perdido");setTimeout(()=>{s.qi++;quiz()},900)}persist()}
function reward(){app.innerHTML='<main class="screen"><div class="shell"><section class="panel"><div class="brand">✨ RECOMPENSA</div><h1>Nível '+s.level+'</h1><p class="subtitle">Escolha avatar e equipamento.</p><h3>Avatar</h3><div class="choices">'+avatars.map(a=>'<button class="choice av">'+a+"</button>").join("")+'</div><h3>Arma</h3><div class="choices">'+weapons.map(w=>'<button class="choice we">'+w+"</button>").join("")+'</div><button id="cont" style="margin-top:16px">Continuar →</button></section></div></main>';document.querySelectorAll(".av").forEach(b=>b.onclick=()=>{s.avatar=b.textContent});document.querySelectorAll(".we").forEach(b=>b.onclick=()=>{s.weapon=b.textContent});document.querySelector("#cont").onclick=()=>{s.qi++;quiz()}}
function arena(){app.innerHTML='<main class="screen"><div class="shell"><div class="topbar"><div><div class="brand">🏟 ARENA CYBERMEDIEVAL</div><h2>Nível '+s.level+" · Batalha por turnos</h2></div><span class="pill" id="players">👥 jogadores: sincronizando</span></div><div class="hud"><span class="pill">❤️ HP '+s.hp+'/100</span><span class="pill">⚔️ '+s.weapon+'</span><span class="pill">⭐ '+s.score+'</span></div><div class="arena"><div class="castle c1"></div><div class="castle c2"></div><div class="healer">🧙‍♀️<div class="small">Curandeira</div></div><div class="player p1">🛡️</div><div class="player p2">⚡</div></div><section class="panel" style="margin-top:14px"><p class="small">Pergunta de batalha</p><h3>Qual comando Linux mostra o diretório atual?</h3><div class="choices"><button class="choice" onclick="battle(true)">pwd</button><button class="choice" onclick="battle(false)">rm</button><button class="choice" onclick="battle(false)">mkdir</button><button class="choice" onclick="battle(false)">touch</button></div></section></div></main>'}
function battle(ok){if(ok){s.score+=150;toast("⚔️ Acerto! Ataque executado! +150")}else toast("❌ Erro! A vez passa ao próximo jogador.");if(s.hp<100&&Math.random()<.3){s.hp=Math.min(100,s.hp+20);toast("🧙‍♀️ Curandeira restaurou +20 HP")}persist()}
async function presence(){if(!sb)return;const c=sb.channel("cybermedieval:"+s.room,{config:{presence:{key:s.name}}});c.on("presence",{event:"sync"},()=>{const p=c.presenceState();const n=Object.values(p).flat().length;const e=document.querySelector("#players");if(e)e.textContent="👥 "+n+" jogadores conectados"}).subscribe(async st=>{if(st==="SUBSCRIBED")await c.track({name:s.name,level:s.level,score:s.score,hp:s.hp})});s.channel=c}
async function persist(){if(!sb)return;try{await sb.from("players").upsert({name:s.name,room_code:s.room,level:s.level,xp:s.xp,score:s.score,avatar:s.avatar,weapon:s.weapon,hp:s.hp},{onConflict:"name"})}catch(e){console.warn(e)}}
lobby();